### ISSUE TITLE
Create Initial Repository

### ISSUE THREAD

**Issue by nyxfor13days** [nyxfor13days/socialcard.sh#1]
### Todo list for Initial Repository Setup

- [x] Create a Next 13 app.
- [x] Setup initial app.
- [x] Setup Prettier and ESLint.
- [x] Setup Husky for formatting and linting before committing.
